export default {
  aab1: require('../img/day/aab1.png'),
  aab2: require('../img/day/aab2.png'),
  account_manage: require('../img/day/account_manage.png'),
  add_h: require('../img/day/add_h.png'),
  add: require('../img/day/add.png'),
  adminA: require('../img/day/adminA.png'),
  authExchangeBlue: require('../img/day/authExchangeBlue.png'),
  boot_bg:require('../img/day/boot_bg.png'),
  candy: require('../img/day/candy.png'),
  cmy_db: require('../img/day/cmy_db.png'),
  cmy_gzh: require('../img/day/cmy_gzh.png'),
  cmy_kydz: require('../img/day/cmy_kydz.png'),
  cmy_qq: require('../img/day/cmy_qq.png'),
  cmy_wb: require('../img/day/cmy_wb.png'),
  cmy_wx: require('../img/day/cmy_wx.png'),
  cmyhead: require('../img/day/cmyhead.png'),
  coinsbg1: require('../img/day/coinsbg1.png'),
  coinsbg2: require('../img/day/coinsbg2.png'),
  details: require('../img/day/details.png'),
  fav: require('../img/day/fav.png'),
  free_mortgage: require('../img/day/free_mortgage.png'),
  
  integral_bg: require('../img/day/integral_bg.png'),
  line_bg: require('../img/day/line_bg.png'),
  lock: require('../img/day/lock.png'),
  logo: require('../img/day/logo1.png'),
  more_h: require('../img/day/more_h.png'),
  more: require('../img/day/more.png'),
  my_activityh: require('../img/day/my_activityh.png'),
  my_community: require('../img/day/my_community.png'),
  my_recovery: require('../img/day/my_recovery.png'),
  navigation: require('../img/day/navigation.png'),
  pool_bg: require('../img/day/pool_bg.png'),
  privatekey: require('../img/day/privatekey.png'),
  publickey: require('../img/day/publickey.png'),
  
  qr: require('../img/day/qr.png'),
  redclose:require('../img/day/redclose.png'),
  resources_f: require('../img/day/resources_f.png'),
  
  resources: require('../img/day/resources.png'),
  

  signed: require('../img/day/signed.png'), 
  signln_bg: require('../img/day/signln_bg.png'),
 
  tab_5_h: require('../img/day/tab_5_h.png'),
  tab_5: require('../img/day/tab_5.png'),
  tokenissue: require('../img/day/tokenissue.png'),
  transactionA: require('../img/day/transactionA.png'),
  transactionB: require('../img/day/transactionB.png'),
  
  transfer: require('../img/day/transfer.png'),
  tx_slide0: require('../img/day/tx_slide0.png'),
  tx_slide1: require('../img/day/tx_slide1.png'),
  vote_node: require('../img/day/vote_node.png'),
  votea_bj: require('../img/day/votea_bj.png'),
  votec_bj: require('../img/day/votec_bj.png'),
  warning: require('../img/day/warning.png'),
  a:require('../img/a.png'),
  account_scan: require('../img/account_scan.png'),
  account_jh: require('../img/accountnumber_jh.png'),
  activation_head: require('../img/activation_head.png'),
  activation_wallet: require('../img/activation_wallet.png'),
  add_plus: require('../img/add_plus.png'),
  Agent: require('../img/Agent.png'),
  AgentInfo_bg: require('../img/AgentInfo_bg.png'),
  al:require('../img/al.png'),
  adminB:require('../img/adminB.png'),
  adminAddA:require('../img/adminAddA.png'),
  adminAddB:require('../img/adminAddB.png'),
  authFrame:require('../img/authFrame.png'),
  b:require('../img/b.png'),
  bottom_log:require('../img/bottom_log.png'),
  bottom_turnin:require('../img/bottom_turnin.png'),
  
  c:require('../img/c.png'),
  Calculation:require('../img/Calculation.png'),
  character_jh:require('../img/character_jh.png'),
  copy:require('../img/copy.png'),
  commonwt: require('../img/commonwt.png'),
  Currency_my: require('../img/Currency_my.png'),
  d: require('../img/d.png'),
  delete_wallet: require('../img/delete_wallet.png'),
  delicon: require('../img/delicon.png'),
  deposit_in: require('../img/deposit_in.png'),
  detailsofm: require('../img/detailsofm.png'),
  difficult: require('../img/difficult.png'),
  eos: require('../img/eos.png'),
  eospark: require('../img/eospark.png'),
  etlogo: require('../img/etlogo.png'),
  fav_h: require('../img/fav_h.png'),
  feedback: require('../img/feedback.png'),
  freemortgage_bg: require('../img/freemortgage_bg.png'),
  Freemortgage: require('../img/Freemortgage.png'),
  goto: require('../img/goto.png'),
  guide: require('../img/guide.png'),
  homecard_bg: require('../img/homecard_bg.png'),
  inb:require('../img/inb.png'),
  Invitation_vote:require('../img/Invitation_vote.png'),
  link:require('../img/link.png'),
  Magnifier:require('../img/Magnifier.png'),
  
  Magnifier_me:require('../img/Magnifier_me.png'),
  ManualSearch: require('../img/ManualSearch.png'),
  Memory:require('../img/Memory.png'),
  MessagePush:require('../img/MessagePush.png'),
  delegatebw_record: require('../img/delegatebw_record.png'),
  mustread: require('../img/mustread.png'),
  network:require('../img/network.png'),
  point_empty:require('../img/point_empty.png'),
  point_full:require('../img/point_full.png'),
  pool_explain: require('../img/pool_explain.png'),
  qrcode:require('../img/qrcode.png'),
  record:require('../img/record.png'),
  refresh:require('../img/refresh.png'),
  resources_bj:require('../img/resources_bj.png'),
  
  
  reveal_h_wallet:require('../img/reveal_h_wallet.png'),
  reveal_wallet:require('../img/reveal_wallet.png'),
  scangray: require('../img/scangray.png'),

  
  share_bottom:require('../img/share_bottom.png'),
  share_img:require('../img/share_img.png'),
 

  share_Size:require('../img/share_Size.png'),
  share_time:require('../img/share_time.png'),
  
  share:require('../img/share.png'),
  share_jh: require('../img/share_jh.png'), 
  sharebg:require('../img/sharebg.png'),
  shift_to:require('../img/shift_to.png'),
  small_bell_h:require('../img/small_bell_h.png'),  
  small_bell:require('../img/small_bell.png'),  
  starempty: require('../img/starempty.png'),
  starfull: require('../img/starfull.png'),
  starhalf: require('../img/starhalf.png'),
  strip_bg:require('../img/strip_bg.png'),
 
  take_out: require('../img/take_out.png'),
  trade_bg: require('../img/trade_bg.png'),
  Tick_h:require('../img/Tick_h.png'),
  Tick:require('../img/Tick.png'),
  accountmange_01:require('../img/accountmange_01.png'),
  turn_out:require('../img/turn_out.png'),
  turninhead:require('../img/turninhead.png'),
  unconfirm:require('../img/unconfirm.png'),
  unconfirm:require('../img/unconfirm.png'),
  vote_h:require('../img/vote_h.png'),
  vote:require('../img/vote.png'),
  votea:require('../img/votea.png'),
  voteb_bj:require('../img/voteb_bj.png'),
  voteb:require('../img/voteb.png'),
  votec:require('../img/votec.png'),
  voted_bj:require('../img/voted_bj.png'),
  voted:require('../img/voted.png'),
  votebc_bj: require('../img/votebc_bj.png'),
  wallet_1:require('../img/wallet_1.png'),
  wallet: require('../img/wallet.png'),
  wallet_h: require('../img/wallet_h.png'),
 
  xin0: require('../img/xin0.png'),
  xin1: require('../img/xin1.png'),
  
  
  tx_ram: require('../img/tx_ram.png'),
  warning_h: require('../img/warning_h.png'),
  //活动
  app12: require('../img/activity/app12.png'),
  app13: require('../img/activity/app13.png'),
  app14: require('../img/activity/app14.png'),
  app15: require('../img/activity/app15.png'),
  app16: require('../img/activity/app16.png'),
  app17: require('../img/activity/app17.png'),
  app18: require('../img/activity/app18.png'),
  app19: require('../img/activity/app19.png'),
  app20: require('../img/activity/app20.png'),
 



  //新版图片
  my_activity: require('../img/newimg/my_activity.png'),
  my_help: require('../img/newimg/my_help.png'),
 
  
  
  transfer: require('../img/newimg/transfer.png'),
  receipt: require('../img/newimg/receipt.png'),
 
 
  up: require('../img/newimg/up.png'),
  up_h:require('../img/newimg/up_h.png'),
  down: require('../img/newimg/down.png'),
  down_h:require('../img/newimg/down_h.png'),
  share_i: require('../img/newimg/share_i.png'),
  tab_1: require('../img/newimg/tab_1.png'),
  tab_2: require('../img/newimg/tab_2.png'),
  tab_3: require('../img/newimg/tab_3.png'),
  tab_4: require('../img/newimg/tab_4.png'),
  tab_1_h: require('../img/newimg/tab_1_h.png'),
  tab_2_h: require('../img/newimg/tab_2_h.png'),
  tab_3_h: require('../img/newimg/tab_3_h.png'),
  tab_4_h: require('../img/newimg/tab_4_h.png'),
  
  
  
  
  //王新版图片
  home_bg: require('../img/wimg/home_bg.png'),
  qr_h: require('../img/wimg/qr_h.png'),
  resources_h: require('../img/wimg/resources_h.png'),
  transfer_h: require('../img/wimg/transfer_h.png'),
  account_manage: require('../img/wimg/account_manage.png'),
  my_aboutus: require('../img/wimg/my_aboutus.png'),
  my_share: require('../img/wimg/my_share.png'),
  my_system: require('../img/wimg/my_system.png'),
  my_wallet: require('../img/wimg/my_wallet.png'),
  my_footbg: require('../img/wimg/my_footbg.png'),
  my_record: require('../img/wimg/my_record.png'),
 
  reveal:require('../img/wimg/reveal.png'),
  reveal_h:require('../img/wimg/reveal_h.png'),

  share_wx:require('../img/wimg/share_wx.png'),
  share_pyq:require('../img/wimg/share_pyq.png'),
  share_qq:require('../img/wimg/share_qq.png'),
  share_wb:require('../img/wimg/share_wb.png'),

  share_banner:require('../img/wimg/share_banner.png'),

  user:require('../img/wimg/user.png'),

  share_bright:require('../img/wimg/share_bright.png'),

  xin_import: require('../img/wimg/xin_import.png'),
  scan: require('../img/wimg/scan.png'),
  xin_add: require('../img/wimg/xin_add.png'),
  xin_qr: require('../img/wimg/xin_qr.png'),

  transfer_float: require('../img/wimg/transfer_float.png'),
  receipt_float: require('../img/wimg/receipt_float.png'),
  resources_float: require('../img/wimg/resources_float.png'),

  qrcode_public: require('../img/wimg/qrcode_public.png'),
  qrcode_wechat: require('../img/wimg/qrcode_wechat.png'),

  Magnifier_ash: require('../img/wimg/Magnifier_ash.png'),

  scanning: require('../img/wimg/scanning.png'),

  //DAPP
  share_dapp:require('../img/wimg/share_dapp.png'),
  copy_dapp:require('../img/wimg/copy_dapp.png'),
  refresh_dapp:require('../img/wimg/refresh_dapp.png'),
  browser_dapp: require('../img/wimg/browser_dapp.png'),
  collection: require('../img/wimg/collection.png'),
  collection_h: require('../img/wimg/collection_h.png'),

  gg_bg01: require('../img/wimg/gg_bg01.jpg'),
  gg_bg02: require('../img/wimg/gg_bg02.jpg'),

  dapp_set:require('../img/dapp_set.png'),
  icon_vote: require('../img/icon_vote.png'),
  //转账
  turnout_pop: require('../img/turnout_pop.png'),
  turnout_delete: require('../img/turnout_delete.png'),
  turnout_add: require('../img/turnout_add.png'),

  nophone: require('../img/nophone.png'),
  love: require('../img/love.png'),
  walletIcon: require('../img/walletIcon.png'),
  lookup: require('../img/lookup.png'),
  Icons_WeChat: require('../img/Icons_WeChat.png'),
  cardbule: require('../img/cardbule.png'),
  
}