export default {
  //白色版图
  aab1: require('../img/day/aab1.png'),
  aab2: require('../img/day/aab2.png'),
  account_manage: require('../img/day/account_manage.png'),
  add_h: require('../img/day/add_h.png'),
  add: require('../img/day/add.png'),
  adminA: require('../img/day/adminA.png'),
  authExchangeBlue: require('../img/day/authExchangeBlue.png'),
  boot_bg:require('../img/day/boot_bg.png'),
  candy: require('../img/day/candy.png'),
  cmy_db: require('../img/day/cmy_db.png'),
  cmy_gzh: require('../img/day/cmy_gzh.png'),
  cmy_kydz: require('../img/day/cmy_kydz.png'),
  cmy_qq: require('../img/day/cmy_qq.png'),
  cmy_wb: require('../img/day/cmy_wb.png'),
  cmy_wx: require('../img/day/cmy_wx.png'),
  cmyhead: require('../img/day/cmyhead.png'),
  coinsbg1: require('../img/day/coinsbg1.png'),
  coinsbg2: require('../img/day/coinsbg2.png'),
  details: require('../img/day/details.png'),
  down: require('../img/day/down.png'),
  fav: require('../img/day/fav.png'),
  free_mortgage: require('../img/day/free_mortgage.png'),
  guide: require('../img/day/guide.png'),
  home_bg: require('../img/day/home_bg.png'),
  integral_bg: require('../img/day/integral_bg.png'),
  line_bg: require('../img/day/line_bg.png'),
  lock: require('../img/day/lock.png'),
  logo: require('../img/day/logo1.png'),
  more_h: require('../img/day/more_h.png'),
  more: require('../img/day/more.png'),
  my_community: require('../img/day/my_community.png'),
  my_help: require('../img/day/my_help.png'),
  my_recovery: require('../img/day/my_recovery.png'),
  my_share: require('../img/day/my_share.png'),
  my_system: require('../img/day/my_system.png'),
  my_wallet: require('../img/day/my_wallet.png'),
  navigation: require('../img/day/navigation.png'),
  privatekey: require('../img/day/privatekey.png'),
  publickey: require('../img/day/publickey.png'),
  qr_h: require('../img/day/qr_h.png'),
  qr: require('../img/day/qr.png'),
  redclose:require('../img/day/redclose.png'),
  resources_f: require('../img/day/resources_f.png'),
  resources_h: require('../img/day/resources_h.png'),
  resources: require('../img/day/resources.png'),
  scan: require('../img/day/scan.png'),
  share_i: require('../img/day/share_i.png'),
  signed: require('../img/day/signed.png'), 
  signln_bg: require('../img/day/signln_bg.png'),
  tab_1: require('../img/day/tab_1.png'),
  tab_2: require('../img/day/tab_2.png'),
  tab_3: require('../img/day/tab_3.png'),
  tab_4: require('../img/day/tab_4.png'),
  tab_5_h: require('../img/day/tab_5_h.png'),
  tab_5: require('../img/day/tab_5.png'),
  tokenissue: require('../img/day/tokenissue.png'),
  transactionA: require('../img/day/transactionA.png'),
  transactionB: require('../img/day/transactionB.png'),
  transfer_h: require('../img/day/transfer_h.png'),
  transfer: require('../img/day/transfer.png'),
  tx_slide0: require('../img/day/tx_slide0.png'),
  tx_slide1: require('../img/day/tx_slide1.png'),
  up: require('../img/day/up.png'),
  vote_node: require('../img/day/vote_node.png'),
  votea_bj: require('../img/day/votea_bj.png'),
  votec_bj: require('../img/day/votec_bj.png'),
  warning: require('../img/day/warning.png'),
  
  //黑色版图
  // aab1: require('../img/aab1.png'),
  // aab2: require('../img/aab2.png'),
  // account_manage:require('../img/account_manage.png'),
  // add_h: require('../img/add_h.png'),
  // add: require('../img/add.png'),
  // adminA:require('../img/adminA.png'),
  // authExchangeBlue:require('../img/authExchangeBlue.png'),
  // boot_bg:require('../img/boot_bg.png'),
  // candy:require('../img/candy.png'),
  // cmy_db:require('../img/cmy_db.png'),
  // cmy_gzh:require('../img/cmy_gzh.png'),
  // cmy_kydz:require('../img/cmy_kydz.png'),
  // cmy_qq:require('../img/cmy_qq.png'),
  // cmy_wb:require('../img/cmy_wb.png'),
  // cmy_wx:require('../img/cmy_wx.png'),
  // cmyhead:require('../img/cmyhead.png'),
  // coinsbg1: require('../img/coinsbg1.png'),
  // coinsbg2: require('../img/coinsbg2.png'),
  // details:require('../img/details.png'),
  // down:require('../img/down.png'),
  // fav: require('../img/fav.png'),
  // free_mortgage: require('../img/free_mortgage.png'),
  // guide:require('../img/guide.png'),
  // home_bg: require('../img/home_bg.png'),
  // integral_bg:require('../img/integral_bg.png'),
  // line_bg:require('../img/line_bg.png'),
  // lock:require('../img/lock.png'),
  // logo:require('../img/logo1.png'),
  // more_h: require('../img/more_h.png'),
  // more:require('../img/more.png'),
  // my_community:require('../img/my_community.png'),
  // my_help:require('../img/my_help.png'),
  // my_recovery:require('../img/my_recovery.png'),
  // my_share:require('../img/my_share.png'),
  // my_system:require('../img/my_system.png'),
  // my_wallet:require('../img/my_wallet.png'),
  // navigation: require('../img/navigation.png'),
  // privatekey:require('../img/privatekey.png'),
  // publickey:require('../img/publickey.png'),
  // qr_h: require('../img/qr_h.png'),
  // qr: require('../img/qr.png'),
  // redclose:require('../img/redclose.png'),
  // resources_f:require('../img/resources_f.png'),
  // resources_h: require('../img/resources_h.png'),
  // resources:require('../img/resources.png'),
  // scan: require('../img/scan.png'),
  // share_i:require('../img/share_i.png'),
  // signed:require('../img/signed.png'), 
  // signln_bg: require('../img/signln_bg.png'),
  // tab_1: require('../img/tab_1.png'),
  // tab_2: require('../img/tab_2.png'),
  // tab_3: require('../img/tab_3.png'),
  // tab_4: require('../img/tab_4.png'),
  // tab_5_h:require('../img/tab_5_h.png'),
  // tab_5: require('../img/tab_5.png'),
  // tokenissue:require('../img/tokenissue.png'),
  // transactionA: require('../img/transactionA.png'),
  // transactionB: require('../img/transactionB.png'),
  // transfer_h: require('../img/transfer_h.png'),
  // transfer:require('../img/transfer.png'),
  // tx_slide0:require('../img/tx_slide0.png'),
  // tx_slide1:require('../img/tx_slide1.png'),
  // up:require('../img/up.png'),
  // vote_node:require('../img/vote_node.png'),
  // votea_bj:require('../img/votea_bj.png'),
  // votec_bj:require('../img/votec_bj.png'),
  // warning:require('../img/warning.png'),

  //公用图
  a:require('../img/a.png'),
  account_scan: require('../img/account_scan.png'),
  activation_head: require('../img/activation_head.png'),
  Agent: require('../img/Agent.png'),
  AgentInfo_bg: require('../img/AgentInfo_bg.png'),
  al:require('../img/al.png'),
  adminB:require('../img/adminB.png'),
  adminAddA:require('../img/adminAddA.png'),
  adminAddB:require('../img/adminAddB.png'),
  authFrame:require('../img/authFrame.png'),
  b:require('../img/b.png'),
  bottom_log:require('../img/bottom_log.png'),
  c:require('../img/c.png'),
  Calculation:require('../img/Calculation.png'),
  copy:require('../img/copy.png'),
  commonwt: require('../img/commonwt.png'),
  d:require('../img/d.png'),
  delicon:require('../img/delicon.png'),
  detailsofm: require('../img/detailsofm.png'),
  difficult: require('../img/difficult.png'),
  down_h:require('../img/down_h.png'),
  eos: require('../img/eos.png'),
  eospark: require('../img/eospark.png'),
  fav_h: require('../img/fav_h.png'),
  feedback: require('../img/feedback.png'),
  freemortgage_bg: require('../img/freemortgage_bg.png'),
  Freemortgage: require('../img/Freemortgage.png'),
  imvote:require('../img/imvote.png'),
  inb:require('../img/inb.png'),
  Invitation_vote:require('../img/Invitation_vote.png'),
  link:require('../img/link.png'),
  Magnifier:require('../img/Magnifier.png'),
  Magnifier_ash:require('../img/Magnifier_ash.png'),
  Magnifier_me:require('../img/Magnifier_me.png'),
  ManualSearch: require('../img/ManualSearch.png'),
  Memory:require('../img/Memory.png'),
  MessagePush:require('../img/MessagePush.png'),
  mustread: require('../img/mustread.png'),
  network:require('../img/network.png'),
  point_empty:require('../img/point_empty.png'),
  point_full:require('../img/point_full.png'),
  qrcode:require('../img/qrcode.png'),
  record:require('../img/record.png'),
  refresh:require('../img/refresh.png'),
  resources_bj:require('../img/resources_bj.png'),
  reveal_h:require('../img/reveal_h.png'),
  reveal:require('../img/reveal.png'),
  reveal_h_wallet:require('../img/reveal_h_wallet.png'),
  reveal_wallet:require('../img/reveal_wallet.png'),
  share_banner:require('../img/share_banner.png'),
  share_bottom:require('../img/share_bottom.png'),
  share_bright:require('../img/share_bright.png'),
  share_img:require('../img/share_img.png'),
  share_pyq:require('../img/share_pyq.png'),
  share_qq:require('../img/share_qq.png'),
  share_Size:require('../img/share_Size.png'),
  share_time:require('../img/share_time.png'),
  share_wx:require('../img/share_wx.png'),
  share:require('../img/share.png'),
  sharebg:require('../img/sharebg.png'),
  shift_to:require('../img/shift_to.png'),
  small_bell_h:require('../img/small_bell_h.png'),  
  small_bell:require('../img/small_bell.png'),  
  starempty: require('../img/starempty.png'),
  starfull: require('../img/starfull.png'),
  starhalf: require('../img/starhalf.png'),
  strip_bg:require('../img/strip_bg.png'),
  tab_1_h: require('../img/tab_1_h.png'),
  tab_2_h: require('../img/tab_2_h.png'),
  tab_3_h: require('../img/tab_3_h.png'),
  tab_4_h: require('../img/tab_4_h.png'),
  Tick_h:require('../img/Tick_h.png'),
  Tick:require('../img/Tick.png'),
  turn_out:require('../img/turn_out.png'),
  turninhead:require('../img/turninhead.png'),
  unconfirm:require('../img/unconfirm.png'),
  up_h:require('../img/up_h.png'),
  unconfirm:require('../img/unconfirm.png'),
  vote_h:require('../img/vote_h.png'),
  vote:require('../img/vote.png'),
  votea:require('../img/votea.png'),
  voteb_bj:require('../img/voteb_bj.png'),
  voteb:require('../img/voteb.png'),
  votec:require('../img/votec.png'),
  voted_bj:require('../img/voted_bj.png'),
  voted:require('../img/voted.png'),
  wallet_1:require('../img/wallet_1.png'),
  wallet: require('../img/wallet.png'),
  wallet_h: require('../img/wallet_h.png'),
  xin_import:require('../img/xin_import.png'),
  xin0:require('../img/xin0.png'),
  xin1:require('../img/xin1.png'),
  tx_ram:require('../img/tx_ram.png'),
  warning_h:require('../img/warning_h.png'),
  dapp_jianyin:require('../img/dapp_jianyin.png'),
  dapp_ite:require('../img/dapp_ite.png'),
  dapp_EOSBET:require('../img/dapp_EOSBET.png'),
  dapp_caicaicai:require('../img/dapp_caicaicai.png'),
}